on: 2
jobs:
  build:
    working_directory: ~/url-shortener
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          BUNDLER_VERSION: 2.1.2
          PGHOST: 127.0.0.1
          PGUSER: admin
          PGPASWWORD: admin
          RAILS_ENV: test
          NODE_ENV: test
      - image: postgres:alpine
        environment:
          BUNDLER_VERSION: 2.1.4
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: url_shortener_test
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: url-shortener-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: url-shortener-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the database
      - run: bundle exec rake db:setup

      # Compile assets
      - run: bundle exec rails assets:precompile

      # Run the tests
      - run: bundle exec rspec
